version: "3.8"
services:
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQLPASSWORD}"
  application:
    build: .
    command: sh -c "/wait && java -jar app.jar"
    ports:
      - "8080:8080"
    environment:
      - WAIT_HOSTS=db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - "spring_profiles_active=prod"
      - "MYSQLPASSWORD=${MYSQLPASSWORD}"
      - "CLIENT_ID=${CLIENT_ID}"
      - "CLIENT_SECRET=${CLIENT_SECRET}"
      - "STARTDATUM=${STARTDATUM}"
      - "STARTUHRZEIT=${STARTUHRZEIT}"
      - "ENDDATUM=${ENDDATUM}"
      - "ENDUHRZEIT=${ENDUHRZEIT}"
      - "ORGANISATOREN=${ORGANISATOREN}"
      - "TUTOREN=${TUTOREN}"