spring:
  flyway:
    schemas: chicken
    create-schemas: true
    url: jdbc:mariadb://localhost:3312/
    user: root
    password: thenotsosecretdevdbpassword
  datasource:
    url: jdbc:mariadb://localhost:3312/chicken
    username: root
    password: thenotsosecretdevdbpassword
    driver-class-name: org.mariadb.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: user

        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token

gruppen:
  organisatoren:
  tutoren:

praktikumszeiten:
  start:
    uhrzeit: "09:30"
    datum: "2022-03-08"
  ende:
    uhrzeit: "13:30"
    datum: "2022-04-08"

lsf:
  domain: "https://lsf.hhu.de/"
  uri: "qisserver/rds?state=verpublish&status=init&vmfile=no&publishid={value}&moduleCall=webInfo&publishConfFile=webInfo&publishSubDir=veranstaltung"